loader_mode: FBDM #FBDM
gpu: '1'
backbone: resnet34 #resnet34, mobilenetv2
data_set: PPM
save_file: 19
img_size: 512
batch_size: 6
num_worker: 8
pretrain_path: ''
lr: 0.0001
weight: 0.0005
port: 23549
epoch: 1000
aug_mixup: false
aug_shadow: true
aug_crop: false
val_per_epoch: 1
show_per_epoch: 10
save_per_epoch: 5


# GFM loader-------------------
rssn_denoise: false
bgPath_denoise: ''
fgPath_denoise: ''
crop_size: 320
val_size: 1600

#PPM
im_path: /data/wjw/work/matting_set/data/PPM-100/train/image/
fg_path: ''
bg_path: ''
gt_path: /data/wjw/work/matting_set/data/PPM-100/train/matte/
val_img_path: /data/wjw/work/matting_set/data/PPM-100/val/image/
val_gt_path: /data/wjw/work/matting_set/data/PPM-100/val/matte/
trimap_path: ''
show_img_path: /data/wjw/work/matting_set/data/PPM-100/val/image/
show_gt_path: /data/wjw/work/matting_set/data/PPM-100/val/matte/

#AM2K
#im_path: /data/wjw/work/matting_set/AM-2K/AM-2K/train/original/
#fg_path: ''
#bg_path: ''
#gt_path: /data/wjw/work/matting_set/AM-2K/AM-2K/train/mask/
#val_img_path: /data/wjw/work/matting_set/AM-2K/AM-2K/validation/original/
#val_gt_path: /data/wjw/work/matting_set/AM-2K/AM-2K/validation/mask/
#trimap_path: ''
#show_img_path: /data/wjw/work/matting_set/AM-2K/AM-2K/validation/original/
#show_gt_path: /data/wjw/work/matting_set/AM-2K/AM-2K/validation/mask/