# public
backend: gloo  # gloo for windows, nccl for linux
gpu: '0'
save_file: 19
batch_size: 8
num_worker: 4
pretrain_path: ''
lr: 0.00001
weight: 0.0005
port: 23548
epoch: 1000
aug_mixup: false
aug_shadow: true
aug_crop: false
val_per_epoch: 1
show_per_epoch: 10
save_per_epoch: 5

# dataset
loader_mode: P3M  # GFM, P3M, FBDM
data_set: AM500

#GFM
backbone: r34
rosta: TT

# GFM loader && P3M loader
rssn_denoise: false
bgPath_denoise: ''
fgPath_denoise: ''
crop_size: 512 # GFM:320; P3M:512

val_size: 1600

# FBDM loader------------------
img_size: 512 # only use in FBDM loader mode

#AIM 500
im_path: F:/matting/AIM-500/original/
fg_path: ''
bg_path: ''
gt_path: F:/matting/AIM-500/mask/
val_img_path: F:/matting/AIM-500/original/
val_gt_path: F:/matting/AIM-500/mask/
trimap_path: ''
show_img_path: F:/matting/AIM-500/original/
show_gt_path: F:/matting/AIM-500/mask/
